/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package retocinco.view;

import javax.swing.JOptionPane;
import retocinco.controller.ProductoController;
import retocinco.model.Producto;
import retocinco.view.frmMenu;

/**
 *
 * @author jotarlo
 */
public class frmProductos extends javax.swing.JFrame {
ProductoController productocontroller = new ProductoController();
String[][] listaProveedor= new String[productocontroller.listaProveedor().size()][2];
String[][] listaExistencia= new String[productocontroller.listaExistencia().size()][2];
String[][] listaCategoria = new String[productocontroller.listaCategoria().size()][2];
    /**
     * Creates new form frmProduct
     */
    public frmProductos() {
        initComponents();
        this.llenarComboProveedor();
        this.llenarComboExistencia();
        this.llenarComboCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigoPro = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cbProveedor = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblIdPro = new javax.swing.JLabel();
        btnListaPro = new javax.swing.JButton();
        btnExistencia = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmbExistencia = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Administración de Productos");

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio Actual");

        jLabel5.setText("Proveedor");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton5.setText("Volver al Inicio");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Codigo producto");

        btnListaPro.setText("Lista de productos");
        btnListaPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaProActionPerformed(evt);
            }
        });

        btnExistencia.setText("Existencias");
        btnExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExistenciaActionPerformed(evt);
            }
        });

        jLabel8.setText("Existencia");

        jLabel9.setText("Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListaPro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(btnExistencia)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGuardar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel2))
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBuscar)
                                        .addGap(29, 29, 29)
                                        .addComponent(btnEditar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEliminar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGap(41, 41, 41)
                                .addComponent(cmbExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lblIdPro)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(btnListaPro)
                    .addComponent(btnExistencia))
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lblIdPro)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnBuscar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        frmMenu menu = new frmMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed
    public void llenarComboProveedor(){
        int index =0;
        for (int i = 0; i < productocontroller.listaProveedor().size(); i++) {
           listaProveedor[i][0] = productocontroller.listaProveedor().get(i).getId_proveedor() + "";
           String data = productocontroller.listaProveedor().get(i).getId_proveedor() + " " + productocontroller.listaProveedor().get(i).getRazon_social() + " " + productocontroller.listaProveedor().get(i).getNIT() + " " + productocontroller.listaProveedor().get(i).getTelefono() + " " + productocontroller.listaProveedor().get(i).getId_direccion() + " " + productocontroller.listaProveedor().get(i).getCorreo() + " " + productocontroller.listaProveedor().get(i).getRepresentante() + " " + productocontroller.listaProveedor().get(i).getSitio_web();
           listaProveedor[i][1]= data;
           this.cbProveedor.addItem(data);
           index++;
        }
        
    }
    public void llenarComboExistencia(){
        int index=0;
        for (int i = 0; i < productocontroller.listaExistencia().size(); i++) {
            listaExistencia[i][0] = productocontroller.listaExistencia().get(i).getId_existencia() + "";
            String data = productocontroller.listaExistencia().get(i).getId_existencia() + " " + productocontroller.listaExistencia().get(i).getNombre();
            listaExistencia[i][1] = data;
            this.cmbExistencia.addItem(data);
            index++;
        }
        
    }
    public void llenarComboCategoria(){
        int index =0;
        for (int i = 0; i < productocontroller.listaCategoria().size(); i++) {
         listaCategoria[i][0] = productocontroller.listaCategoria().get(i).getId_categoria() + "";
         String data = productocontroller.listaCategoria().get(i).getId_categoria() + " " + productocontroller.listaCategoria().get(i).getNombre_categoria()+ " " + productocontroller.listaCategoria().get(i).getDescripcion();
       listaCategoria[i][1]= data;
       this.cmbCategoria.addItem(data);
       index++;
        }
    }
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        int seleccion =0;
        int seleccion_u =0;
        int seleccion_d=0;
        for (int i = 0; i < listaProveedor.length; i++) {
            if(listaProveedor[i][1].equals(cbProveedor.getSelectedItem().toString())){
                seleccion= Integer.parseInt(listaProveedor[i][0]);
            }
        }
        for (int i = 0; i < listaExistencia.length; i++) {
            if(listaExistencia[i][1].equals(cmbExistencia.getSelectedItem().toString())){
                seleccion_u= Integer.parseInt(listaExistencia[i][0]);
            }
        }
        for (int i = 0; i < listaCategoria.length; i++) {
            if(listaCategoria[i][1].equals(cmbCategoria.getSelectedItem().toString())){
                seleccion_d= Integer.parseInt(listaCategoria[i][0]);
            }
        }
        int codi = Integer.parseInt(txtCodigoPro.getText());
        double pre = Double.parseDouble(txtPrecio.getText());
        Producto producto= new Producto(codi,txtNombre.getText(),pre,seleccion,seleccion_u,seleccion_d
        );
        productocontroller.asignarProducto(producto);
        this.limpiarTexto();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        int codiPro = Integer.parseInt(txtCodigoPro.getText().trim());
        this.limpiarTexto();
        Producto pro = this.productocontroller.existeProducto(codiPro);
        if(pro != null){
            this.lblIdPro.setText(Integer.toString(pro.getId_producto()));
            this.txtCodigoPro.setText(Integer.toString(pro.getCodigoProducto()));
            this.txtNombre.setText(pro.getNombre());
            this.txtPrecio.setText(Double.toString(pro.getPrecioActual()));
            this.txtNombre.setText(pro.getNombre());
         
        }else{
            JOptionPane.showMessageDialog(this, "No se encontro el producto con el codigo : " + codiPro);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int codi = Integer.parseInt(txtCodigoPro.getText());
         int seleccion =0;
        int seleccion_u =0;
        int seleccion_d=0;
        for (int i = 0; i < listaProveedor.length; i++) {
            if(listaProveedor[i][1].equals(cbProveedor.getSelectedItem().toString())){
                seleccion= Integer.parseInt(listaProveedor[i][0]);
            }
        }
        for (int i = 0; i < listaExistencia.length; i++) {
            if(listaExistencia[i][1].equals(cmbExistencia.getSelectedItem().toString())){
                seleccion_u= Integer.parseInt(listaExistencia[i][0]);
            }
        }
        for (int i = 0; i < listaCategoria.length; i++) {
            if(listaCategoria[i][1].equals(cmbCategoria.getSelectedItem().toString())){
                seleccion_d= Integer.parseInt(listaCategoria[i][0]);
            }
        }
        double pre = Double.parseDouble(txtPrecio.getText());
        Producto producto= new Producto(txtNombre.getText(),pre,seleccion,seleccion_u,seleccion_d
        );
        producto.setCodigoProducto(codi);
        productocontroller.editarProducto(producto);
        this.limpiarTexto();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnListaProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaProActionPerformed
        // TODO add your handling code here:
        frmListaProductos frmpro = new frmListaProductos();
        frmpro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListaProActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtCodigoPro.getText());
        boolean seElimino = this.productocontroller.eliminarProducto(codigo);
        if (seElimino == true){
            JOptionPane.showMessageDialog(this, "SE ELIMINO EL PRODUCTO");
        }else{
            JOptionPane.showMessageDialog(this, " NO SE ELIMINO EL PRODUCTO");
            this.limpiarTexto();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnExistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExistenciaActionPerformed
        // TODO add your handling code here:
        frmExistencia frmexis = new frmExistencia();
        frmexis.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnExistenciaActionPerformed
public void limpiarTexto(){
    txtCodigoPro.setText("");
    txtNombre.setText("");
    txtPrecio.setText("");
   
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExistencia;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnListaPro;
    private javax.swing.JComboBox<String> cbProveedor;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbExistencia;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblIdPro;
    private javax.swing.JTextField txtCodigoPro;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
