/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.universidadmintic75.views;

import com.mycompany.universidadmintic75.models.Facultad;
import com.mycompany.universidadmintic75.Principal;
import com.mycompany.universidadmintic75.controllers.FacultadController;
import com.mycompany.universidadmintic75.controllers.UniversidadController;
import com.mycompany.universidadmintic75.models.Profesor;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Bicho
 */
public class FrmFacultades extends javax.swing.JFrame {

    UniversidadController universidadController = new UniversidadController();
    /**
     * Creates new form FrmFacultades
     */
    public FrmFacultades() {
        initComponents();
    }
    
    private void llenarListaFacultades(){
        DefaultListModel model = new DefaultListModel();
        
        int index = 0;
        for(Facultad fac: universidadController.getListaFacultades()){
            String data = fac.getNombre() + " " + fac.getTelefono();
            model.add(index, data);
            index++;
        }
        lstFacultades.setModel(model);
    }
    
    public void llenarComboFacultades(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnFacultades = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFacultades = new javax.swing.JList<>();
        jpAdministracion = new javax.swing.JPanel();
        lblNombreFacultad = new javax.swing.JLabel();
        txtFacultad = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jpnProfesores = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbFacultadProfesor = new javax.swing.JComboBox<>();
        btnAsignarProfesor = new javax.swing.JButton();
        txtProfesor = new javax.swing.JTextField();
        txtTelefonoProfe = new javax.swing.JTextField();
        txtDocumentoProfesor = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Adminstración de Facultades");

        jScrollPane2.setViewportView(lstFacultades);

        javax.swing.GroupLayout jpnFacultadesLayout = new javax.swing.GroupLayout(jpnFacultades);
        jpnFacultades.setLayout(jpnFacultadesLayout);
        jpnFacultadesLayout.setHorizontalGroup(
            jpnFacultadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFacultadesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 160, Short.MAX_VALUE))
        );
        jpnFacultadesLayout.setVerticalGroup(
            jpnFacultadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFacultadesLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Facultades", jpnFacultades);

        lblNombreFacultad.setText("Facultad");

        lblTelefono.setText("Telefono");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAdministracionLayout = new javax.swing.GroupLayout(jpAdministracion);
        jpAdministracion.setLayout(jpAdministracionLayout);
        jpAdministracionLayout.setHorizontalGroup(
            jpAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAdministracionLayout.createSequentialGroup()
                .addGroup(jpAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAdministracionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpAdministracionLayout.createSequentialGroup()
                                .addComponent(lblNombreFacultad)
                                .addGap(18, 18, 18)
                                .addComponent(txtFacultad))
                            .addGroup(jpAdministracionLayout.createSequentialGroup()
                                .addComponent(lblTelefono)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jpAdministracionLayout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(0, 34, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpAdministracionLayout.setVerticalGroup(
            jpAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAdministracionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreFacultad)
                    .addComponent(txtFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnBuscar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Administración", jpAdministracion);

        jLabel2.setText("Nombre");

        jLabel3.setText("Telefono");

        jLabel4.setText("Documento");

        jLabel5.setText("Facultad");

        cmbFacultadProfesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ciencias", "sociales", "ingles" }));

        btnAsignarProfesor.setText("Asignar");
        btnAsignarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnProfesoresLayout = new javax.swing.GroupLayout(jpnProfesores);
        jpnProfesores.setLayout(jpnProfesoresLayout);
        jpnProfesoresLayout.setHorizontalGroup(
            jpnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProfesoresLayout.createSequentialGroup()
                .addGroup(jpnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAsignarProfesor)
                    .addGroup(jpnProfesoresLayout.createSequentialGroup()
                        .addGroup(jpnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(jpnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbFacultadProfesor, 0, 241, Short.MAX_VALUE)
                            .addComponent(txtProfesor)
                            .addComponent(txtTelefonoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDocumentoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 70, Short.MAX_VALUE))
        );
        jpnProfesoresLayout.setVerticalGroup(
            jpnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnProfesoresLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefonoProfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDocumentoProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnProfesoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbFacultadProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAsignarProfesor)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Profesores", jpnProfesores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        Facultad facul = new Facultad(txtFacultad.getText(), txtTelefono.getText());
        this.universidadController.crearFacultad(facul);
        
        this.llenarListaFacultades();
        this.limpiarCajasTextoAdministracion();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void limpiarCajasTextoAdministracion(){
        txtFacultad.setText("");
        txtTelefono.setText("");
    }
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombreFacultad = txtFacultad.getText().trim();
        this.limpiarCajasTextoAdministracion();
        Facultad fac = this.universidadController.existeFacultad(nombreFacultad);
        if (fac != null){
             this.txtFacultad.setText(fac.getNombre());
             this.txtTelefono.setText(fac.getTelefono());
        }else{
            JOptionPane.showMessageDialog(this, "No se encontro la facultad: " + nombreFacultad);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String nombreFacultad = txtFacultad.getText();
        boolean esFacultad = false;
        for(Facultad fac: Principal.uniMintic.getFacultades()){
            if (fac.getNombre().equals(nombreFacultad)){
                fac.setTelefono(txtTelefono.getText());
                JOptionPane.showMessageDialog(this, "Facultad Actualizada correctamente");
                esFacultad = true;
                break;
            }
        }
        if (!esFacultad)
            JOptionPane.showMessageDialog(this, "No se encuentra la facultad");
        else{
            this.llenarListaFacultades();
        }
        this.limpiarCajasTextoAdministracion();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String nombreFacultad = txtFacultad.getText();
        boolean seElimino = this.universidadController.eliminarFacultad(nombreFacultad);
        if (seElimino == false)
            JOptionPane.showMessageDialog(this, "No se encontró la facultad: " + nombreFacultad);
        else{
            JOptionPane.showMessageDialog(this, "Se elimnó la Facultad: " + nombreFacultad);
            this.llenarListaFacultades();
            this.limpiarCajasTextoAdministracion();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAsignarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarProfesorActionPerformed
        Profesor profe = new Profesor(txtProfesor.getText(), txtTelefonoProfe.getText(), txtDocumentoProfesor.getText());
        String nombreFacultad = cmbFacultadProfesor.getSelectedItem().toString();
        //JOptionPane.showMessageDialog(this, nombreFacultad);
        FacultadController facController = new FacultadController(nombreFacultad);
        facController.asignarProfesor(profe);
    }//GEN-LAST:event_btnAsignarProfesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFacultades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFacultades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFacultades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFacultades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFacultades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAsignarProfesor;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> cmbFacultadProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jpAdministracion;
    private javax.swing.JPanel jpnFacultades;
    private javax.swing.JPanel jpnProfesores;
    private javax.swing.JLabel lblNombreFacultad;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JList<String> lstFacultades;
    private javax.swing.JTextField txtDocumentoProfesor;
    private javax.swing.JTextField txtFacultad;
    private javax.swing.JTextField txtProfesor;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoProfe;
    // End of variables declaration//GEN-END:variables
}
